<?php

namespace Container3qnyIlF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MO_EF1hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MO.eF1h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authService' => ['privates', 'App\\Service\\AuthService', 'getAuthServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'verificationService' => ['privates', 'App\\Service\\EmailVerificationService', 'getEmailVerificationServiceService', true],
        ], [
            'authService' => 'App\\Service\\AuthService',
            'em' => '?',
            'verificationService' => 'App\\Service\\EmailVerificationService',
        ]);

        if (isset($container->privates['.service_locator.MO.eF1h'])) {
            return $container->privates['.service_locator.MO.eF1h'];
        }

        return $container->privates['.service_locator.MO.eF1h'] = $instance;
    }
}
