<?php

namespace Container3qnyIlF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailVerificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailVerificationService' shared autowired service.
     *
     * @return \App\Service\EmailVerificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmailVerificationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmailSender.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }
        $b = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }
        $c = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }
        $d = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }

        $instance = new \App\Service\EmailVerificationService($a, new \App\Service\EmailSender(new \Symfony\Component\Mailer\Mailer($b, $c, $d)));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }

        return $container->privates['App\\Service\\EmailVerificationService'] = $instance;
    }
}
