<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHOq3FRI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHOq3FRI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHOq3FRI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHOq3FRI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHOq3FRI\App_KernelDevDebugContainer([
    'container.build_hash' => 'HOq3FRI',
    'container.build_id' => '5e8d40ac',
    'container.build_time' => 1770065499,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHOq3FRI');
